apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cloudtrace-agent
  namespace: acm-workshop--tenant
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/IAMServiceAccount/gke-primary-pool
spec:
  memberFrom:
    serviceAccountRef:
      name: gke-primary-pool
      namespace: acm-workshop--tenant
  resourceRef:
    kind: Project
    external: acm-workshop--tenant
  role: roles/cloudtrace.agent
