apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: primary
  namespace: acm-workshop--tenant
  annotations:
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/ContainerCluster/gke
spec:
  clusterRef:
    name: gke
  initialNodeCount: 1
  location: us-east1
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    imageType: COS_CONTAINERD
    diskSizeGb: 100
    diskType: pd-ssd
    labels:
      gke.io/nodepool: primary
    machineType: n2d-standard-4
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    serviceAccountRef:
      name: 
