apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: gke
  namespace: acm-workshop--tenant
  annotations:
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/ContainerCluster/gke
spec:
  location: global
  authority:
    issuer: https://container.googleapis.com/v1/projects/$\{TENANT_PROJECT_ID\}/locations/$\{GKE_LOCATION\}/clusters/$\{GKE_NAME\}
  endpoint:
    gkeCluster:
      resourceRef:
        name: gke
