apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: gke
  namespace: acm-workshop--tenant
  annotations:
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/ComputeSubnetwork/gke,compute.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/ComputeRouter/gke
spec:
  natIpAllocateOption: AUTO_ONLY
  region: us-east1
  routerRef:
    name: gke
  sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
  subnetwork:
  - subnetworkRef:
      name: gke
    sourceIpRangesToNat:
    - ALL_IP_RANGES
