apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: gke
  namespace: acm-workshop--tenant
  annotations:
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/acm-workshop--tenant/ComputeNetwork/gke
spec:
  networkRef:
    name: gke
  region: us-east1
